//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.BookStoreServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WebApplication3")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookStoreServiceReference.IBookStoreWebService")]
    public interface IBookStoreWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/GetAllBooks", ReplyAction="http://tempuri.org/IBookStoreWebService/GetAllBooksResponse")]
        WebApplication3.BookStoreServiceReference.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/GetAllBooks", ReplyAction="http://tempuri.org/IBookStoreWebService/GetAllBooksResponse")]
        System.Threading.Tasks.Task<WebApplication3.BookStoreServiceReference.Book[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/AddBook", ReplyAction="http://tempuri.org/IBookStoreWebService/AddBookResponse")]
        bool AddBook(WebApplication3.BookStoreServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/AddBook", ReplyAction="http://tempuri.org/IBookStoreWebService/AddBookResponse")]
        System.Threading.Tasks.Task<bool> AddBookAsync(WebApplication3.BookStoreServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/DeleteBook", ReplyAction="http://tempuri.org/IBookStoreWebService/DeleteBookResponse")]
        bool DeleteBook(string field, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/DeleteBook", ReplyAction="http://tempuri.org/IBookStoreWebService/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(string field, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/SearchBook", ReplyAction="http://tempuri.org/IBookStoreWebService/SearchBookResponse")]
        WebApplication3.BookStoreServiceReference.Book[] SearchBook(string field, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStoreWebService/SearchBook", ReplyAction="http://tempuri.org/IBookStoreWebService/SearchBookResponse")]
        System.Threading.Tasks.Task<WebApplication3.BookStoreServiceReference.Book[]> SearchBookAsync(string field, string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookStoreWebServiceChannel : WebApplication3.BookStoreServiceReference.IBookStoreWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookStoreWebServiceClient : System.ServiceModel.ClientBase<WebApplication3.BookStoreServiceReference.IBookStoreWebService>, WebApplication3.BookStoreServiceReference.IBookStoreWebService {
        
        public BookStoreWebServiceClient() {
        }
        
        public BookStoreWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookStoreWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStoreWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStoreWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication3.BookStoreServiceReference.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<WebApplication3.BookStoreServiceReference.Book[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public bool AddBook(WebApplication3.BookStoreServiceReference.Book book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task<bool> AddBookAsync(WebApplication3.BookStoreServiceReference.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public bool DeleteBook(string field, string value) {
            return base.Channel.DeleteBook(field, value);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(string field, string value) {
            return base.Channel.DeleteBookAsync(field, value);
        }
        
        public WebApplication3.BookStoreServiceReference.Book[] SearchBook(string field, string value) {
            return base.Channel.SearchBook(field, value);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.BookStoreServiceReference.Book[]> SearchBookAsync(string field, string value) {
            return base.Channel.SearchBookAsync(field, value);
        }
    }
}
