//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.BookPurchaseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookPurchaseServiceReference.IBookPurchaseWebService")]
    public interface IBookPurchaseWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookPurchaseWebService/PurchaseBooks", ReplyAction="http://tempuri.org/IBookPurchaseWebService/PurchaseBooksResponse")]
        WebApplication3.BookPurchaseServiceReference.BookPurchaseResponse PurchaseBooks(WebApplication3.BookPurchaseServiceReference.BookPurchaseInfo request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookPurchaseWebService/PurchaseBooks", ReplyAction="http://tempuri.org/IBookPurchaseWebService/PurchaseBooksResponse")]
        System.Threading.Tasks.Task<WebApplication3.BookPurchaseServiceReference.BookPurchaseResponse> PurchaseBooksAsync(WebApplication3.BookPurchaseServiceReference.BookPurchaseInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookPurchaseInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookPurchaseInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public float budget;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<int, int> items;
        
        public BookPurchaseInfo() {
        }
        
        public BookPurchaseInfo(float budget, System.Collections.Generic.Dictionary<int, int> items) {
            this.budget = budget;
            this.items = items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookPurchaseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookPurchaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool result;
        
        public BookPurchaseResponse() {
        }
        
        public BookPurchaseResponse(string response, bool result) {
            this.response = response;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookPurchaseWebServiceChannel : WebApplication3.BookPurchaseServiceReference.IBookPurchaseWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookPurchaseWebServiceClient : System.ServiceModel.ClientBase<WebApplication3.BookPurchaseServiceReference.IBookPurchaseWebService>, WebApplication3.BookPurchaseServiceReference.IBookPurchaseWebService {
        
        public BookPurchaseWebServiceClient() {
        }
        
        public BookPurchaseWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookPurchaseWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookPurchaseWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookPurchaseWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.BookPurchaseServiceReference.BookPurchaseResponse WebApplication3.BookPurchaseServiceReference.IBookPurchaseWebService.PurchaseBooks(WebApplication3.BookPurchaseServiceReference.BookPurchaseInfo request) {
            return base.Channel.PurchaseBooks(request);
        }
        
        public string PurchaseBooks(float budget, System.Collections.Generic.Dictionary<int, int> items, out bool result) {
            WebApplication3.BookPurchaseServiceReference.BookPurchaseInfo inValue = new WebApplication3.BookPurchaseServiceReference.BookPurchaseInfo();
            inValue.budget = budget;
            inValue.items = items;
            WebApplication3.BookPurchaseServiceReference.BookPurchaseResponse retVal = ((WebApplication3.BookPurchaseServiceReference.IBookPurchaseWebService)(this)).PurchaseBooks(inValue);
            result = retVal.result;
            return retVal.response;
        }
        
        public System.Threading.Tasks.Task<WebApplication3.BookPurchaseServiceReference.BookPurchaseResponse> PurchaseBooksAsync(WebApplication3.BookPurchaseServiceReference.BookPurchaseInfo request) {
            return base.Channel.PurchaseBooksAsync(request);
        }
    }
}
