//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.FindZodiaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FindZodiaService.ZodiaFinderServiceSoap")]
    public interface ZodiaFinderServiceSoap {
        
        // CODEGEN: Generating message contract since element name zodiac from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindZodiac", ReplyAction="*")]
        WebApplication2.FindZodiaService.FindZodiacResponse FindZodiac(WebApplication2.FindZodiaService.FindZodiacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindZodiac", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.FindZodiaService.FindZodiacResponse> FindZodiacAsync(WebApplication2.FindZodiaService.FindZodiacRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindZodiacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindZodiac", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.FindZodiaService.FindZodiacRequestBody Body;
        
        public FindZodiacRequest() {
        }
        
        public FindZodiacRequest(WebApplication2.FindZodiaService.FindZodiacRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindZodiacRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string zodiac;
        
        public FindZodiacRequestBody() {
        }
        
        public FindZodiacRequestBody(string zodiac) {
            this.zodiac = zodiac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindZodiacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindZodiacResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.FindZodiaService.FindZodiacResponseBody Body;
        
        public FindZodiacResponse() {
        }
        
        public FindZodiacResponse(WebApplication2.FindZodiaService.FindZodiacResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindZodiacResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindZodiacResult;
        
        public FindZodiacResponseBody() {
        }
        
        public FindZodiacResponseBody(string FindZodiacResult) {
            this.FindZodiacResult = FindZodiacResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZodiaFinderServiceSoapChannel : WebApplication2.FindZodiaService.ZodiaFinderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZodiaFinderServiceSoapClient : System.ServiceModel.ClientBase<WebApplication2.FindZodiaService.ZodiaFinderServiceSoap>, WebApplication2.FindZodiaService.ZodiaFinderServiceSoap {
        
        public ZodiaFinderServiceSoapClient() {
        }
        
        public ZodiaFinderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZodiaFinderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiaFinderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiaFinderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.FindZodiaService.FindZodiacResponse WebApplication2.FindZodiaService.ZodiaFinderServiceSoap.FindZodiac(WebApplication2.FindZodiaService.FindZodiacRequest request) {
            return base.Channel.FindZodiac(request);
        }
        
        public string FindZodiac(string zodiac) {
            WebApplication2.FindZodiaService.FindZodiacRequest inValue = new WebApplication2.FindZodiaService.FindZodiacRequest();
            inValue.Body = new WebApplication2.FindZodiaService.FindZodiacRequestBody();
            inValue.Body.zodiac = zodiac;
            WebApplication2.FindZodiaService.FindZodiacResponse retVal = ((WebApplication2.FindZodiaService.ZodiaFinderServiceSoap)(this)).FindZodiac(inValue);
            return retVal.Body.FindZodiacResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.FindZodiaService.FindZodiacResponse> WebApplication2.FindZodiaService.ZodiaFinderServiceSoap.FindZodiacAsync(WebApplication2.FindZodiaService.FindZodiacRequest request) {
            return base.Channel.FindZodiacAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.FindZodiaService.FindZodiacResponse> FindZodiacAsync(string zodiac) {
            WebApplication2.FindZodiaService.FindZodiacRequest inValue = new WebApplication2.FindZodiaService.FindZodiacRequest();
            inValue.Body = new WebApplication2.FindZodiaService.FindZodiacRequestBody();
            inValue.Body.zodiac = zodiac;
            return ((WebApplication2.FindZodiaService.ZodiaFinderServiceSoap)(this)).FindZodiacAsync(inValue);
        }
    }
}
